wmt2021 = {
    "Europarl v10": {
        "README": "http://www.statmt.org/europarl/v10/README",
        "training-monolingual": [
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.cs.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.cs.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.en.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.es.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.fi.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.fr.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.lt.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.pl.tsv.gz",
            "http://www.statmt.org/europarl/v10/training-monolingual/europarl-v10.pt.tsv.gz"
        ],
        "training": [
            "http://www.statmt.org/europarl/v10/training/europarl-v10.cs-en.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.cs-pl.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.de-en.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.de-fr.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.es-pt.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.fi-en.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.fr-en.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.lt-en.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.pl-en.tsv.gz",
            "http://www.statmt.org/europarl/v10/training/europarl-v10.sv-en.tsv.gz"
        ]
    },
    "ParaCrawl v7.1": [
        "https://s3.amazonaws.com/web-language-models/paracrawl/release7.1/en-cs.txt.gz",
        "https://s3.amazonaws.com/web-language-models/paracrawl/release7.1/en-de.txt.gz",
        "https://s3.amazonaws.com/web-language-models/paracrawl/release7.1/en-is.txt.gz",
        "http://www.kecl.ntt.co.jp/icl/lirg/jparacrawl/release/2.0/bitext/en-ja.tar.gz",
        "http://data.statmt.org/wmt21/translation-task/zh-en/paracrawl.wmt21.en-zh.gz",
        "http://data.statmt.org/wmt19/translation-task/fr-de/bitexts/",
    ],
    "ParaCrawl v8": [
        "http://data.statmt.org/wmt21/translation-task/paracrawl8/en-ha.tar",
        "http://data.statmt.org/wmt21/translation-task/paracrawl8/en-ru.tar"
    ]
    "Common Crawl corpus": [
        "http://www.statmt.org/wmt13/training-parallel-commoncrawl.tgz",
        "http://data.statmt.org/wmt19/translation-task/fr-de/bitexts/"
    ],
    "News Commentary v16": {
        "documents.tgz": "http://data.statmt.org/news-commentary/v16/documents.tgz",
        "training-monolingual": [
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.ar.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.cs.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.de.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.en.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.es.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.fr.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.hi.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.id.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.it.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.ja.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.kk.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.nl.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.nl.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.pt.gz",
            "http://data.statmt.org/news-commentary/v16/training-monolingual/news-commentary-v16.ru.gz"
        ],
        "training": [
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-cs.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-de.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-en.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-es.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-fr.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-hi.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-id.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-it.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-ja.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ar-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-de.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-en.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-es.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-fr.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-hi.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-id.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-it.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-ja.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.cs-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.de-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.de-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.de-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.de-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-es.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-fr.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-hi.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-id.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-it.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-ja.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.es-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.es-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.en-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-hi.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-id.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-it.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-ja.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.fr-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-id.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-it.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-ja.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.hi-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.id-it.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.id-ja.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.id-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.id-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.id-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.id-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.id-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.it-ja.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.it-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.it-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.it-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.it-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.it-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ja-kk.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ja-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ja-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ja-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ja-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.kk-nl.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.kk-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.kk-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.kk-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.nl-pt.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.nl-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.nl-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.pt-ru.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.pt-zh.tsv.gz",
            "http://data.statmt.org/news-commentary/v16/training/news-commentary-v16.ru-zh.tsv.gz"
        ],
    },
    "Wiki Titles v3": [
        "http://data.statmt.org/wikititles/v3/wikititles-v3.bn-hi.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ca-es.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ca-pt.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ca-ro.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.cs-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.de-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.de-fr.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.es-pt.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.es-ro.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ha-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ig-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.is-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ja-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ps-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.pt-ro.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.ru-en.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.xh-zu.tsv",
        "http://data.statmt.org/wikititles/v3/wikititles-v3.zh-en.tsv"
    ],
    "Tilde Rapid corpus": [
        "http://data.statmt.org/wmt20/translation-task/rapid/RAPID_2019.cs-en.xlf.gz",
        "http://data.statmt.org/wmt20/translation-task/rapid/RAPID_2019.de-en.xlf.gz",
    ],
    "CCMT Corpus": [
        "http://www.hackcha.cn/cwmt_data/casia2015.zip",
        "http://www.hackcha.cn/cwmt_data/casict2011.zip",
        "http://www.hackcha.cn/cwmt_data/casict2015.zip",
        "http://www.hackcha.cn/cwmt_data/datum2015.zip",
        "http://www.hackcha.cn/cwmt_data/datum2017.zip",
        "http://www.hackcha.cn/cwmt_data/neu2017.zip"
    ],
    "WikiMatrix": [
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.cs-en.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.de-en.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.de-fr.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.en-is.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.en-ja.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.en-pl.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.en-ru.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.en-ta.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.en-te.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.en-zh.langid.tsv.gz",
        "http://data.statmt.org/wmt21/translation-task/WikiMatrix/WikiMatrix.v1.hi-ta.langid.tsv.gz"
    ],
    "ParIce": "http://parice.arnastofnun.is/data/parice_filtered.zip",
    "Back-translated news": {
        "ru-en": [
            "http://data.statmt.org/wmt20/translation-task/back-translation/ru-en/news.en.gz",
            "http://data.statmt.org/wmt20/translation-task/back-translation/ru-en/news.en.translatedto.ru.gz",
            "http://data.statmt.org/wmt20/translation-task/back-translation/ru-en/news.ru.gz",
            "http://data.statmt.org/wmt20/translation-task/back-translation/ru-en/news.ru.translatedto.en.gz"
        ],
        "zh-en": [
            "http://data.statmt.org/wmt20/translation-task/back-translation/zh-en/news.en.gz",
            "http://data.statmt.org/wmt20/translation-task/back-translation/zh-en/news.translatedto.zh.gz"
        ]
    },
    "Japanese-English Subtitle Corpus": "https://nlp.stanford.edu/projects/jesc/data/split.tar.gz",
    "The Kyoto Free Translation Task Corpus": "http://www.phontron.com/kftt/download/kftt-data-1.0.tar.gz"
    "TED Talks":"http://data.statmt.org/wmt20/translation-task/ja-en/ted.en-ja.tgz"
    "Khamenei corpus": "http://data.statmt.org/wmt21/translation-task/ha-en/khamenei.v1.ha-en.tsv",
    "English-Hausa Opus corpus": "http://data.statmt.org/wmt21/translation-task/ha-en/opus.ha-en.tsv"
    "CC-Aligned": [
        "http://data.statmt.org/wmt21/translation-task/cc-aligned/bn-hi.tar",
        "http://data.statmt.org/wmt21/translation-task/cc-aligned/xh-zu.tar"
    ],
    "News crawl": {
        "cs": [
            "http://data.statmt.org/news-crawl/cs/news.2007.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2008.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2009.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2010.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2011.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2012.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2013.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2014.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2015.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2016.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2017.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2018.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2019.cs.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/cs/news.2020.cs.shuffled.deduped.gz"
        ],
        "de": [
            "http://data.statmt.org/news-crawl/de/news.2007.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2008.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2009.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2010.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2011.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2012.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2013.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2014.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2015.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2016.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2017.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2018.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2019.de.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/de/news.2020.de.shuffled.deduped.gz"
        ],
        "en": [
            "http://data.statmt.org/news-crawl/en/news.2007.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2008.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2009.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2010.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2011.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2012.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2013.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2014.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2015.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2016.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2017.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2018.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2019.en.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/en/news.2020.en.shuffled.deduped.gz"
        ],
        "fr": [
            "http://data.statmt.org/news-crawl/fr/news.2007.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2008.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2009.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2010.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2011.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2012.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2013.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2014.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2015.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2016.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2017.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2018.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2019.fr.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/fr/news.2020.fr.shuffled.deduped.gz",
        ],
        "ha": [
            "http://data.statmt.org/news-crawl/ha/news.2008.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2009.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2010.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2011.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2012.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2013.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2014.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2018.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2019.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2020.M6.ha.filtered.gz",
            "http://data.statmt.org/news-crawl/ha/news.2020.ha.shuffled.deduped.gz"
        ],
        "is": [
            "http://data.statmt.org/news-crawl/is/news.2020.is.shuffled.deduped.gz"
        ],
        "ja": [
            "http://data.statmt.org/news-crawl/ja/news.2019.ja.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ja/news.2020.ja.shuffled.deduped.gz"
        ],
        "ru": [
            "http://data.statmt.org/news-crawl/ru/news.2008.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2009.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2010.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2011.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2012.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2013.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2014.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2015.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2016.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2017.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2018.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2019.ru.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/ru/news.2020.ru.shuffled.deduped.gz"
        ],
        "zh": [
            "http://data.statmt.org/news-crawl/zh/news.2008.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2010.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2011.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2012.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2013.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2014.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2015.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2016.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2017.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2018.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2019.zh.shuffled.deduped.gz",
            "http://data.statmt.org/news-crawl/zh/news.2020.zh.shuffled.deduped.gz"
        ]
    },
    "News discussions": {
        "README": "http://data.statmt.org/news-discussions/README",
        "en": [
            "http://data.statmt.org/news-discussions/en/news-discuss.2011.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2012.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2013.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2014.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2015.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2016.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2017.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2018.en.filtered.gz",
            "http://data.statmt.org/news-discussions/en/news-discuss.2019.en.filtered.gz"
        ],
        "fr": [
            "http://data.statmt.org/news-discussions/fr/news-discuss.2006.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2007.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2008.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2009.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2010.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2011.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2012.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2013.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2014.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2015.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2016.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2017.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2018.fr.filtered.gz",
            "http://data.statmt.org/news-discussions/fr/news-discuss.2019.fr.filtered.gz"
        ],
        "json": [
            "http://data.statmt.org/news-discussions/json/news-site-comments-2020-09-24.tgz"
        ]
    },
    "Common Crawl": [
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/wmt16/deduped/cs.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/wmt16/deduped/de.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/wmt16/deduped/en-new.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/ngrams/fr/deduped/fr.deduped.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/ngrams/ha/deduped/ha.deduped.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/ngrams/is/deduped/is.deduped.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/ngrams/ja/deduped/ja.deduped.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/wmt16/deduped/ru.xz",
        "http://web-language-models.s3-website-us-east-1.amazonaws.com/ngrams/zh/deduped/zh.deduped.xz"
    ],

    "Icelandic Gigaword": [
        "https://repository.clarin.is/repository/xmlui/bitstream/handle/20.500.12537/41/IGC1.20.05.zip",
        "https://repository.clarin.is/repository/xmlui/bitstream/handle/20.500.12537/33/IGC2.20.05.zip"
    ],
    "Extended Common Crawl": [
        # Bengali
        "http://data.statmt.org/wmt21/translation-task/cc-mono/bn.txt.xz",
        # German
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.0.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.1.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.2.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.3.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.4.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.5.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.6.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.7.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.8.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/de.9.txt.xz",

        # French
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.0.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.1.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.2.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.3.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.4.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.5.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.6.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.7.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.8.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/fr.9.txt.xz",

        # Hausa
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ha.txt.xz",

        # Hindi
        "http://data.statmt.org/wmt21/translation-task/cc-mono/hi.txt.xz",

        # Japanese
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.0.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.1.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.2.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.3.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.4.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.5.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.6.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.7.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.8.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ja.9.txt.xz",

        # Russian
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.0.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.1.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.10.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.11.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.12.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.13.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.14.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.15.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.16.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.17.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.18.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.19.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.2.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.20.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.21.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.22.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.23.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.24.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.25.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.26.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.27.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.28.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.29.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.3.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.30.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.31.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.32.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.33.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.34.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.35.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.36.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.37.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.38.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.39.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.4.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.40.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.41.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.42.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.43.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.45.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.46.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.47.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.48.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.49.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.5.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.6.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.7.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.8.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/ru.9.txt.xz",

        # Xhosa
        "http://data.statmt.org/wmt21/translation-task/cc-mono/xh.txt.xz",

        # Chinese (simplified)
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.0.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.1.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.2.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.3.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.4.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.5.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.6.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.7.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.8.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zhs.9.txt.xz",

        # Chinese (traditional)
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.0.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.1.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.2.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.3.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.4.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.5.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.6.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.7.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.8.txt.xz",
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zht.9.txt.xz",

        # Zulu
        "http://data.statmt.org/wmt21/translation-task/cc-mono/zu.txt.xz"
    ]
}
